# run before: sudo sysctl -w vm.max_map_count=262144

version: '2.2'
services:
  esslave0:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: esslave0
    environment:
      - node.name=esslave0
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=esslave1,esslave2, esslave3
      - cluster.initial_master_nodes=esslave0,esslave1,esslave2, esslave3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    cpus: 1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataslave0:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic


  esslave1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: esslave1
    environment:
      - node.name=esslave1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=esslave0,esslave2,esslave3
      - cluster.initial_master_nodes=esslave0,esslave1,esslave2, esslave3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    cpus: 1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataslave1:/usr/share/elasticsearch/data
    networks:
      - elastic



  esslave2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: esslave2
    environment:
      - node.name=esslave2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=esslave0,esslave1, esslave3
      - cluster.initial_master_nodes=esslave0,esslave1,esslave2, esslave3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    cpus: 1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataslave2:/usr/share/elasticsearch/data
    networks:
      - elastic


  esslave3:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
      container_name: esslave3
      environment:
        - node.name=esslave3
        - cluster.name=es-docker-cluster
        - discovery.seed_hosts=esslave0,esslave1, esslave2
        - cluster.initial_master_nodes=esslave0,esslave1,esslave2
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      cpus: 1
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - dataslave2:/usr/share/elasticsearch/data
      networks:
        - elastic


# Web interface to display the statistics
  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.5.1'
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://esslave0:9200
    ports:
      - '5601:5601'
    links:
      - esslave0
      - esslave1
      - esslave2
      - esslave3
    networks:
      - elastic


# Web interface to manage elasticsearch cluster
  headPlugin:
    image: 'mobz/elasticsearch-head:5'
    container_name: head
    ports:
      - '9100:9100'
    networks:
      - elastic


# Container to make the benchmark of elastic search cluster
  rally:
    image: elastic/rally:latest
    container_name: rally
    command: "esrally --track=metricbeat --target-host=esslave0:9200,esslave1:9200,esslave2:9200,esslave3:9200 --pipeline=benchmark-only
    --report-format=csv --report-file=.rally/benchmarks/results/2019-02-03-metricbeat-4slave.csv"
    volumes:
      - ./rally:/rally/.rally
    networks:
      - elastic
    links:
      - kibana
      - headPlugin
#        condition: service_healthy


volumes:
  dataslave0:
    driver: local
  dataslave1:
    driver: local
  dataslave2:
    driver: local


networks:
  elastic:
    driver: bridge