# run before: sudo sysctl -w vm.max_map_count=262144

version: '2.2'

x-default-es:
  &default-es
  image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
  environment:
    - node.name=esslave0
    - cluster.name=es-docker-cluster
    - discovery.seed_hosts=${SLAVE_4}
    - cluster.initial_master_nodes=esslave0
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  cpus: 1
  ulimits:
    memlock:
      soft: -1
      hard: -1
  networks:
    - elastic

services:
  rally:
    image: elastic/rally:latest
    container_name: rally
    command: "esrally --track=metricbeat --target-host=${SLAVE_4} --pipeline=benchmark-only
      --report-format=csv --report-file=.rally/benchmarks/results/${TEST_DATE}-metricbeat-4slaves.csv"
    volumes:
      - ./rally:/rally/.rally
    networks:
      - elastic
    links:
      - esslave0
      - esslave1
      - esslave2
      - esslave3

  esslave0:
    container_name: esslave0
    <<: *default-es
    ports:
      - 9200:9200
    volumes:
      - dataslave0:/usr/share/elasticsearch/data


  esslave1:
    container_name: esslave1
    <<: *default-es
    volumes:
      - dataslave1:/usr/share/elasticsearch/data

  esslave2:
    container_name: esslave2
    <<: *default-es
    volumes:
      - dataslave2:/usr/share/elasticsearch/data

  esslave3:
    container_name: esslave3
    <<: *default-es
    volumes:
      - dataslave3:/usr/share/elasticsearch/data


volumes:
  dataslave0:
    driver: local
  dataslave1:
    driver: local
  dataslave2:
    driver: local
  dataslave3:
    driver: local


networks:
  elastic:
    driver: bridge